// ---------- effect parameter schema ----------
const FX = [
  { id:'vhs', name:'VHS', hint:'chroma shift · scanlines · bleed', on:false, open:false, params:[
    { k:'aberration', label:'Aberration (H)', min:0, max:20, step:.5, def:6, env:1, envd:1 },
    { k:'scanline',   label:'Scanlines', min:0, max:1,  step:.01, def:.35 },
    { k:'bleed',      label:'Bleed', min:0, max:12, step:.5, def:3 },
    { k:'tracking',   label:'Tracking', min:0, max:1, step:.01, def:.3, env:1 },
    { k:'wobble',     label:'Wobble', min:0, max:20, step:.5, def:5 },
    { k:'wobmode',    label:'Wobble Pattern', type:'select', def:0,
      options:[[0,'Wave'],[1,'Pulse'],[2,'Jitter'],[3,'Step'],[4,'Drift']] },
  ]},
  { id:'glitch', name:'Slice', hint:'directional cuts · shift / duplicate / freeze / invert / solid fill + RGB split', on:false, open:false, params:[
    { k:'amount',   label:'Amount', min:0, max:1, step:.01, def:.4, env:1, envd:1 },
    { k:'direction',label:'Direction', type:'select', def:0, options:[[0,'Horizontal'],[1,'Vertical'],[2,'Both']] },
    { k:'fill',     label:'Break Method', type:'select', def:0, options:[[0,'Shift'],[1,'Duplicate'],[2,'Freeze'],[3,'Invert'],[4,'Solid Black'],[5,'Solid White']] },
    { k:'slices',   label:'Slices', min:1, max:40, step:1, def:14 },
    { k:'jitter',   label:'Uneven', min:0, max:1, step:.01, def:0 },
    { k:'shift',    label:'Shift', min:0, max:120, step:1, def:40, env:1, envd:1, show:s=> (s.fill|0)<=1 },
    { k:'edge',     label:'Edge', type:'select', def:0, options:[[0,'Hard'],[3,'Round'],[1,'Ramp'],[2,'Overshoot']], show:s=> (s.fill|0)===0 },
    { k:'edgew',    label:'Edge (px)', min:2, max:40, step:1, def:12, show:s=> (s.fill|0)===0 && (s.edge|0)!==0 },
    { k:'rgb',      label:'RGB Split (V)', min:0, max:30, step:.5, def:8, env:1, envd:1 },
    { k:'applyto',  label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage', label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'noise', name:'Noise', hint:'grain — luma / colour / salt & pepper', on:false, open:false, params:[
    { k:'grain',    label:'Grain',   min:0, max:1, step:.01, def:.18, env:1, envd:1 },
    { k:'size',     label:'Grain Size', min:0, max:1, step:.01, def:0 },
    { k:'smooth',   label:'Smooth', min:0, max:1, step:.01, def:0, show:s=> (s.size||0)>0 },
    { k:'type',     label:'Type', type:'select', def:0, options:[[0,'Luma'],[1,'Chroma'],[2,'Salt & Pepper'],[3,'Colour Specks']] },
    { k:'flicker',  label:'Flicker',  min:0, max:1, step:.01, def:.1, env:1, envd:1 },
  ]},
  { id:'color', name:'Color', hint:'grade · fade', on:false, open:false, params:[
    { k:'saturate', label:'Saturation',   min:0, max:2, step:.01, def:1.2 },
    { k:'contrast', label:'Contrast', min:0, max:2, step:.01, def:1.1 },
    { k:'bright',   label:'Brightness', min:.5, max:2, step:.01, def:1, env:1 },
    { k:'hue',      label:'Hue Rotate', min:-180, max:180, step:1, def:0 },
    { k:'tint',     label:'Tint (blue⇄orange)', min:-1, max:1, step:.01, def:0 },
    { k:'vignette', label:'Vignette', min:0, max:1, step:.01, def:.3 },
  ]},
  { id:'roll', name:'Roll', hint:'scroll / vertical roll (wraps around)', on:false, open:false, params:[
    { k:'hspeed', label:'H-Scroll', min:-8, max:8, step:.05, def:.3 },
    { k:'hstep',  label:'Step', min:0, max:1, step:.01, def:0 },
    { k:'vspeed', label:'V-Roll', min:-8, max:8, step:.05, def:0 },
    { k:'ease',   label:'Speed Curve', type:'select', def:0,
      options:[[0,'Linear'],[1,'Ease In'],[2,'Ease Out'],[3,'Ease In-Out'],[4,'Pendulum']] },
    { k:'band',   label:'Roll Band', min:0, max:1, step:.01, def:.4 },
  ]},
  { id:'film', name:'Film 8mm', hint:'old film · dust · scratches · burn (shake = VHS Wobble)', on:false, open:false, params:[
    { k:'dust',    label:'Dust', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'scratch', label:'Scratches', min:0, max:1, step:.01, def:.3, env:1 },
    { k:'sepia',   label:'Sepia', min:0, max:1, step:.01, def:.5 },
    { k:'burn',    label:'Burn/Flicker', min:0, max:1, step:.01, def:.3, env:1 },
  ]},
  { id:'mosh', name:'Datamosh', hint:'directional block smear / freeze / duplicate / random paste / frame accumulation + pixel sort + channel jitter', on:false, open:false, params:[
    { k:'intensity', label:'Intensity',   min:0, max:1, step:.01, def:.5, env:1, envd:1 },
    { k:'push',      label:'Push Direction', type:'select', def:0, options:[[0,'Flow'],[1,'Down'],[2,'Up'],[3,'Left'],[4,'Right'],[5,'Radial']] },
    { k:'mode',      label:'Block Mode', type:'select', def:0, options:[[0,'Smear'],[1,'Freeze'],[2,'Duplicate'],[3,'Random Paste'],[4,'Accumulate']] },
    { k:'reset',     label:'Reset Count / 3 sec', min:1, max:12, step:1, def:1, show:s=> (s.mode|0)===4 },
    { k:'blocks',    label:'Blocks', min:0, max:1, step:.01, def:.5 },
    { k:'bloom',     label:'Bloom (max repeat)', min:1, max:4, step:1, def:1 },
    { k:'vert',      label:'Vertical Drift', min:0, max:1, step:.01, def:0 },
    { k:'sort',      label:'Pixel Sort', min:0, max:1, step:.01, def:.3 },
    { k:'chaos',     label:'Jitter', min:0, max:1, step:.01, def:.6 },
    { k:'rate',      label:'Change Rate', min:1, max:30, step:1, def:10 },
    { k:'applyto',   label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage',  label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'jpeg', name:'JPEG Glitch', hint:'real byte corruption — entropy melt / quant tone-shift / Huffman collapse', on:false, open:false, params:[
    { k:'amount',  label:'Corruption', min:0, max:1, step:.01, def:.3 },
    { k:'mix',     label:'Output Mix', min:0, max:1, step:.01, def:1 },
    { k:'density', label:'Damage Density', min:0, max:1, step:.01, def:1 },
    { k:'burst',   label:'Burst Size (bytes)', min:1, max:16, step:1, def:1 },
    { k:'spread',  label:'Spread', min:0, max:1, step:.01, def:1 },
    { k:'mutation',label:'Mutation', type:'select', def:0, options:[[0,'Replace'],[1,'Bit Flip (gentle)'],[2,'XOR'],[3,'Zero'],[4,'FF'],[5,'Copy Previous'],[6,'Swap Chunks']] },
    { k:'where',   label:'Damage Position', type:'select', def:0, options:[[0,'Whole'],[1,'Start'],[2,'Middle'],[3,'End'],[4,'Sweep'],[5,'Random Window']] },
    { k:'window',  label:'Window Size', min:.02, max:1, step:.01, def:.35, show:s=> (s.where|0)!==0 },
    { k:'target',  label:'Target', type:'select', def:0, options:[[0,'Entropy (block melt)'],[1,'Quant table (tone shift)'],[2,'Huffman table (collapse)']] },
    { k:'tablepart',label:'Table Part', type:'select', def:0, options:[[0,'All'],[1,'Primary (Luma / DC)'],[2,'Secondary (Chroma / AC)']], show:s=> (s.target|0)!==0 },
    { k:'safety',  label:'Safety', type:'select', def:1, options:[[0,'Stable'],[1,'Balanced'],[2,'Wild']] },
    { k:'quality', label:'Quality (coarse)', min:.05, max:.95, step:.01, def:.35 },
    { k:'frames',  label:'Frames', min:1, max:16, step:1, def:6 },
  ]},
  { id:'png', name:'PNG Glitch', hint:'real · scanline-filter corruption (H/V/diagonal bleed + noise)', on:false, open:false, params:[
    { k:'amount', label:'Bleed (filter)', min:0, max:1, step:.01, def:.3 },
    { k:'noise',  label:'Random Noise', min:0, max:1, step:.01, def:.2 },
    { k:'mix',    label:'Output Mix', min:0, max:1, step:.01, def:1 },
    { k:'density',label:'Damage Density', min:0, max:1, step:.01, def:1 },
    { k:'burst',  label:'Burst Size (bytes)', min:1, max:16, step:1, def:1 },
    { k:'spread', label:'Spread', min:0, max:1, step:.01, def:1 },
    { k:'mutation',label:'Mutation', type:'select', def:0, options:[[0,'Replace'],[1,'Bit Flip (gentle)'],[2,'XOR'],[3,'Zero'],[4,'FF'],[5,'Copy Previous'],[6,'Swap Chunks']] },
    { k:'where',  label:'Damage Position', type:'select', def:0, options:[[0,'Whole'],[1,'Start'],[2,'Middle'],[3,'End'],[4,'Sweep'],[5,'Random Window']] },
    { k:'window', label:'Window Size', min:.02, max:1, step:.01, def:.35, show:s=> (s.where|0)!==0 },
    { k:'dir',    label:'Bleed Dir', type:'select', def:0,
      options:[[0,'Mix'],[1,'Horizontal (Sub)'],[2,'Vertical (Up)'],[3,'Diagonal (Paeth)'],[4,'Diagonal (Average)'],[5,'None / Raw']] },
    { k:'pattern',label:'Filter Pattern', type:'select', def:0, options:[[0,'Banded'],[1,'Per Row'],[2,'Alternating'],[3,'Sweep']] },
    { k:'band',   label:'Band Size (rows)', min:1, max:64, step:1, def:16, show:s=> (s.pattern|0)!==1 },
    { k:'frames', label:'Frames', min:1, max:16, step:1, def:6 },
  ]},
  { id:'compress', name:'Compression', hint:'heavy-JPEG look — blocky DCT · chroma bleed · banding', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'sub',    label:'Chroma Subsample', type:'select', def:0, options:[[0,'4:4:4 (off)'],[1,'4:2:2 (half H)'],[2,'4:2:0 (quarter)']] },
    { k:'chroma', label:'Chroma Bleed', min:0, max:1, step:.01, def:.5 },
    { k:'ring',   label:'Ringing', min:0, max:1, step:.01, def:0, env:1 },
    { k:'soft',   label:'Softness (detail loss)', min:0, max:1, step:.01, def:0, env:1 },
    { k:'block',  label:'Block', min:4, max:16, step:2, def:8 },
  ]},
  { id:'dct', name:'DCT Glitch', hint:'real 8×8 DCT — flatten / quantise / DC-shift / scramble coefficients (live)', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'mix',    label:'Mix', min:0, max:1, step:.01, def:.7, env:1 },
    { k:'mode',   label:'Mode', type:'select', def:0, options:[[0,'Flatten (blocky)'],[1,'Quantise (banding)'],[2,'DC Shift (block jumps)'],[3,'Scramble AC (ringing)']] },
    { k:'block',  label:'Block', type:'select', def:8, options:[[8,'8 px'],[16,'16 px']] },
    { k:'chroma', label:'Colour', min:0, max:1, step:.01, def:.5 },
  ]},
  { id:'pixsort', name:'Pixel Sort', hint:'reorder runs of pixels by a chosen key (glitch-art staple)', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.85, env:1 },
    { k:'key',    label:'Sort By', type:'select', def:0,
      options:[[0,'Lightness'],[1,'Hue'],[2,'Saturation'],[3,'Intensity'],[4,'Min RGB']] },
    { k:'ivl',    label:'Interval', type:'select', def:0,
      options:[[0,'Threshold'],[1,'Random'],[2,'Edges'],[3,'Waves'],[4,'Whole line']] },
    { k:'chance', label:'Sort Chance', min:0, max:1, step:.01, def:1 },
    // Threshold only feeds the two intervals that cut on the picture; Whole line has no run length
    { k:'thresh', label:'Threshold / Edge', min:0, max:1, step:.01, def:.5, show:s=> s.ivl===0 || s.ivl===2 },
    { k:'dir',    label:'Direction', type:'select', def:0, options:[[0,'Rows →'],[1,'Columns ↓'],[2,'Both'],[3,'Angled']] },
    { k:'angle',  label:'Angle', min:0, max:179, step:1, def:45, show:s=> s.dir===3 },
    { k:'len',    label:'Max Length', min:0, max:1, step:.01, def:.6, show:s=> s.ivl!==4 },
  ]},
  { id:'databend', name:'Data Shear', hint:'raw-byte / stride error — diagonal shear + rainbow', on:false, open:false, params:[
    { k:'amount',   label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'skew',     label:'Skew', min:0, max:1, step:.01, def:.4 },
    { k:'scramble', label:'Scramble', min:0, max:1, step:.01, def:.4 },
    { k:'chunk',    label:'Chunk Size (rows)', min:1, max:64, step:1, def:1 },
    { k:'speed',    label:'Speed', min:0, max:8, step:1, def:2 },
    { k:'applyto',  label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage', label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'bmpmisread', name:'BMP Row Misread', hint:'wrong row width · padding · bottom-up reinterpretation', on:false, open:false, params:[
    { k:'amount',  label:'Amount', min:0, max:1, step:.01, def:.75, env:1 },
    { k:'width',   label:'Width Error', min:-32, max:32, step:1, def:7, env:1 },
    { k:'padding', label:'Row Padding', min:0, max:24, step:1, def:4, env:1 },
    { k:'flip',    label:'Row Order', type:'select', def:0, options:[[0,'Top-down'],[1,'BMP bottom-up']] },
    { k:'applyto', label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage',label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'wrongfmt', name:'Wrong Format', hint:'reinterpret the raw frame with the wrong pixel layout — planar YUV triple-ghost / stride shear / bit-depth', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1, envd:1 },
    { k:'mode',   label:'Layout', type:'select', def:0, options:[[0,'Planar (triple-ghost)'],[1,'Stride Shear'],[2,'Bit Depth (16→8)'],[3,'Channel Planar']] },
    { k:'chunk',  label:'Chunk Size (rows)', min:1, max:64, step:1, def:1, show:s=> (s.mode|0)===1 },
    { k:'roam',   label:'Roam', min:0, max:1, step:.01, def:0, env:1 },
    { k:'applyto',label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage',label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'rle', name:'RLE Databend', hint:'real — genuine TGA-style RLE8 packet stream, corrupt the run headers → colour runs desync and smear', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1, envd:1 },
    { k:'colors', label:'Colours', min:2, max:128, step:1, def:48 },
    { k:'speed',  label:'Speed', min:1, max:12, step:1, def:4 },
  ]},
  { id:'gif', name:'Indexed / GIF', hint:'256-colour palette · dither · scramble / colour-cycle / streaks', on:false, open:false, params:[
    { k:'colors', label:'Colours', min:2, max:64, step:1, def:16 },
    { k:'dither', label:'Dither', min:0, max:1, step:.01, def:.4 },
    { k:'glitch', label:'Palette FX', type:'select', def:0,
      options:[[0,'None'],[1,'Scramble'],[2,'Colour Cycle'],[3,'Index Streaks']] },
    { k:'amount', label:'FX Amount', min:0, max:1, step:.01, def:.5, env:1 },
  ]},
  { id:'sonify', name:'Sonify', hint:'audio-style databend on the raw byte stream — echo / reverse / reverb / tremolo', on:false, open:false, params:[
    { k:'mode',   label:'Effect', type:'select', def:0, options:[[0,'Echo'],[1,'Reverse'],[2,'Reverb'],[3,'Tremolo'],[4,'Ring Mod'],[5,'Overdrive'],[6,'Stutter'],[7,'Decimate']] },
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'delay',  label:'Delay / Rate', min:1, max:100, step:1, def:30, env:1 },
  ]},
  { id:'byteshift', name:'Byte Shift', hint:'raw reinterpret — channel roll + diagonal shear', on:false, open:false, params:[
    { k:'amount', label:'Shift', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'roll',   label:'Channel Roll', type:'select', def:1, options:[[0,'RGB'],[1,'GBR'],[2,'BRG']] },
    { k:'skew',   label:'Skew', min:0, max:1, step:.01, def:.3 },
    { k:'chunk',  label:'Chunk Size (rows)', min:1, max:64, step:1, def:1 },
    { k:'applyto',label:'Apply To', type:'select', def:0, options:[[0,'Whole'],[1,'Bright'],[2,'Dark'],[3,'Edges'],[4,'Saturated']] },
    { k:'coverage',label:'Coverage', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'bitplane', name:'Bit-plane', hint:'split bit planes — displace / XOR / drop for banded glitch', on:false, open:false, params:[
    { k:'mode',   label:'Mode', type:'select', def:0, options:[[0,'Plane Shift'],[1,'XOR'],[2,'Drop Low']] },
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'bits',   label:'Bit Split', min:2, max:7, step:1, def:6 },
  ]},
  { id:'webp', name:'WebP Glitch', hint:'real WebP re-encode + byte corruption (VP8 predictive glitch)', on:false, open:false, params:[
    { k:'amount', label:'Corruption', min:0, max:1, step:.01, def:.3 },
    { k:'mix',    label:'Output Mix', min:0, max:1, step:.01, def:1 },
    { k:'density',label:'Damage Density', min:0, max:1, step:.01, def:1 },
    { k:'burst',  label:'Burst Size (bytes)', min:1, max:16, step:1, def:1 },
    { k:'spread', label:'Spread', min:0, max:1, step:.01, def:1 },
    { k:'mutation',label:'Mutation', type:'select', def:0, options:[[0,'Replace'],[1,'Bit Flip (gentle)'],[2,'XOR'],[3,'Zero'],[4,'FF'],[5,'Copy Previous'],[6,'Swap Chunks']] },
    { k:'where',  label:'Damage Position', type:'select', def:0, options:[[0,'Whole'],[1,'Start'],[2,'Middle'],[3,'End'],[4,'Sweep'],[5,'Random Window']] },
    { k:'window', label:'Window Size', min:.02, max:1, step:.01, def:.35, show:s=> (s.where|0)!==0 },
    { k:'target', label:'Payload Target', type:'select', def:0, options:[[0,'Whole Safe Payload'],[1,'Early Prediction'],[2,'Late Residual']] },
    { k:'safety', label:'Safety', type:'select', def:1, options:[[0,'Stable'],[1,'Balanced'],[2,'Wild']] },
    { k:'quality',label:'Quality', min:1, max:90, step:1, def:40 },
    { k:'frames', label:'Frames', min:1, max:12, step:1, def:6 },
  ]},
  { id:'gifg', name:'GIF Glitch', hint:'real GIF encode + byte corruption — LZW image data & colour table (separate)', on:false, open:false, params:[
    { k:'data',    label:'Data (LZW)', min:0, max:1, step:.01, def:.5 },
    { k:'palette', label:'Palette', min:0, max:1, step:.01, def:.4 },
    { k:'palmode', label:'Palette Method', type:'select', def:0, options:[[0,'Replace'],[1,'Rotate'],[2,'Swap'],[3,'Invert'],[4,'Channel Roll']] },
    { k:'paltarget',label:'Palette Target', type:'select', def:0, options:[[0,'All'],[1,'Red'],[2,'Green'],[3,'Blue'],[4,'Bright Entries'],[5,'Dark Entries']] },
    { k:'colors',  label:'Colours', min:2, max:256, step:1, def:64 },
    { k:'iterations',label:'Iterations (0 = Auto)', min:0, max:6, step:1, def:0 },
    { k:'mix',     label:'Output Mix', min:0, max:1, step:.01, def:1 },
    { k:'density', label:'Damage Density', min:0, max:1, step:.01, def:1 },
    { k:'burst',   label:'Burst Size (bytes)', min:1, max:16, step:1, def:1 },
    { k:'spread',  label:'Spread', min:0, max:1, step:.01, def:1 },
    { k:'mutation',label:'Mutation', type:'select', def:0, options:[[0,'Replace'],[1,'Bit Flip (gentle)'],[2,'XOR'],[3,'Zero'],[4,'FF'],[5,'Copy Previous'],[6,'Swap Chunks']] },
    { k:'where',   label:'Damage Position', type:'select', def:0, options:[[0,'Whole'],[1,'Start'],[2,'Middle'],[3,'End'],[4,'Sweep'],[5,'Random Window']] },
    { k:'window',  label:'Window Size', min:.02, max:1, step:.01, def:.35, show:s=> (s.where|0)!==0 },
    { k:'frames',  label:'Frames', min:1, max:12, step:1, def:6 },
  ]},
  { id:'audio', name:'Audio Databend', hint:'real — route the raw bytes through a WebAudio graph (echo / reverb / crush / filter / distortion / compressor / chorus)', on:false, open:false, params:[
    { k:'mode',   label:'Effect', type:'select', def:0, options:[[0,'Echo'],[1,'Reverb'],[2,'Bit-crush'],[3,'Low-pass Sweep'],[4,'High-pass'],[5,'Band-pass'],[6,'Comb'],[7,'Distortion'],[8,'Compressor'],[9,'Chorus']] },
    { k:'layout', label:'Byte Layout', type:'select', def:0, options:[[0,'Planar RGB'],[1,'Interleaved Rows'],[2,'Interleaved Columns'],[3,'Rotated Planes (GBR)']] },
    { k:'tune',   label:'DSP Controls', type:'select', def:0, options:[[0,'Auto (legacy response)'],[1,'Custom']] },
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1, envd:1 },
    { k:'mix',    label:'Output Mix', min:0, max:1, step:.01, def:1 },
    { k:'wet',    label:'DSP Wet', min:0, max:1, step:.01, def:1 },
    { k:'delay',  label:'Delay', min:0, max:1, step:.01, def:.45, show:s=> (s.tune|0)===1 && [0,6].includes(s.mode|0) },
    { k:'feedback',label:'Feedback', min:0, max:1, step:.01, def:.55, show:s=> (s.tune|0)===1 && [0,6].includes(s.mode|0) },
    { k:'cutoff', label:'Cutoff', min:0, max:1, step:.01, def:.5, show:s=> (s.tune|0)===1 && [3,4,5].includes(s.mode|0) },
    { k:'resonance',label:'Resonance', min:0, max:1, step:.01, def:.45, show:s=> (s.tune|0)===1 && [3,4,5].includes(s.mode|0) },
    { k:'drive',  label:'Drive / Crush', min:0, max:1, step:.01, def:.5, show:s=> (s.tune|0)===1 && [2,7,8].includes(s.mode|0) },
    { k:'rate',   label:'Chorus Rate', min:0, max:1, step:.01, def:.4, show:s=> (s.tune|0)===1 && (s.mode|0)===9 },
    { k:'depth',  label:'Chorus Depth', min:0, max:1, step:.01, def:.5, show:s=> (s.tune|0)===1 && (s.mode|0)===9 },
    { k:'frames', label:'Steps', min:1, max:8, step:1, def:5 },
  ]},
  { id:'degauss', name:'Degauss', hint:'degaussing CRT — the picture ripples and the colour goes impure', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'sway',   label:'Screen Ripple', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'freq',   label:'Shimmer', min:1, max:8, step:1, def:4 },
    { k:'color',  label:'Rainbow', min:0, max:1, step:.01, def:.7 },
    { k:'curve',  label:'Curve', type:'select', def:1,
      options:[[0,'Constant (never settles)'],[1,'Peak (settles)'],[2,'Pulse'],[3,'Build → Drop'],[4,'Stutter'],[5,'Swell'],[6,'Drop → Build'],[7,'Bounce'],[8,'Wander']] },
    { k:'rate',   label:'Rate', min:1, max:8, step:1, def:2, show:s=> [2,4,7,8].includes(s.curve|0) },
  ]},
  { id:'warp', name:'Warp', hint:'horizontal displacement — heat-haze / underwater / shear', on:false, open:false, params:[
    { k:'amp',   label:'Amplitude', min:0, max:10, step:.25, def:5, env:1 },
    // Jitter/Step have no spatial wave to set a frequency on, and Twist shears the whole frame;
    // Pulse swells in place, so it never reads a speed
    { k:'freq',  label:'Frequency', min:1, max:20, step:1, def:6, show:s=> ![2,3,5].includes(s.warpmode|0) },
    { k:'speed', label:'Speed', min:0, max:6, step:1, def:2, show:s=> (s.warpmode|0)!==1 },
    { k:'warpmode', label:'Pattern', type:'select', def:0,
      options:[[0,'Wave'],[1,'Pulse'],[2,'Jitter'],[3,'Step'],[4,'Drift'],[5,'Twist'],[6,'Beat'],[7,'Zigzag']] },
  ]},
  { id:'pixelate', name:'Pixelate', hint:'mosaic / retro blocks (Envelope can pulse block size)', on:false, open:false, params:[
    { k:'size', label:'Block Size', min:1, max:48, step:1, def:8, env:1 },
    { k:'mix',  label:'Mix', min:0, max:1, step:.01, def:1, env:1 },
    { k:'fade',  label:'Fade', type:'select', def:0,
      options:[[0,'Even'],[1,'Right'],[2,'Left'],[3,'Bottom'],[4,'Top'],[5,'Bright areas'],[6,'Dark areas']] },
    { k:'cover', label:'Coverage', min:0, max:1, step:.01, def:.5, env:1, show:s=> s.fade!==0 },
  ]},
  { id:'hud', name:'HUD / Text', hint:'5 text slots · tokens {date} {time} {ctr} {rec} {n}', on:false, open:false, params:[
    { k:'layout',  label:'Preset', type:'select', def:3,
      options:[[0,'REC ●'],[1,'▶ PLAY'],[2,'Timestamp'],[3,'Camcorder'],[4,'Security Cam'],
               [5,'TV Channel'],[6,'VCR Play'],[7,'ON AIR']] },
    { k:'tl', label:'Top-left',     type:'text', def:'{rec}REC',   ph:'{rec}REC' },
    { k:'tr', label:'Top-right',    type:'text', def:'{time}{n}SP',ph:'{time}' },
    { k:'c',  label:'Centre',       type:'text', def:'',           ph:'text' },
    { k:'bl', label:'Bottom-left',  type:'text', def:'▶',          ph:'▶ PLAY' },
    { k:'br', label:'Bottom-right', type:'text', def:'{date}',     ph:'{date} {time}' },
    { k:'color',   label:'Text Color', type:'select', def:0,
      options:[[0,'White'],[1,'Amber'],[2,'Green'],[3,'Red'],[4,'Cyan'],[5,'Black']] },
    { k:'size',    label:'Size', min:.5, max:2.5, step:.1, def:1 },
    { k:'opacity', label:'Opacity', min:0, max:1, step:.01, def:.9 },
  ]},
  { id:'bloom', name:'Bloom', hint:'glow / light bleed — Halation lifts the whole frame (high-key)', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'size',   label:'Radius', min:1, max:30, step:1, def:8 },
    { k:'glow',   label:'Halation (high-key)', min:0, max:1, step:.01, def:0, env:1 },
  ]},
  { id:'leak', name:'Light Leak', hint:'warm light bleeds in from an edge and drifts over the loop — brightens', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'tone',   label:'Tone', type:'select', def:0, options:[[0,'Warm'],[1,'Gold'],[2,'Red'],[3,'White'],[4,'Cool']] },
    { k:'pos',    label:'From', type:'select', def:0, options:[[0,'Left'],[1,'Right'],[2,'Top'],[3,'Bottom'],[4,'Corner']] },
    { k:'size',   label:'Size', min:0, max:1, step:.01, def:.5 },
    { k:'drift',  label:'Drift', min:0, max:1, step:.01, def:.4 },
  ]},
  // ---- hype / dopamine ----
  { id:'gold', name:'Metallic', hint:'metallic tone-map with a shine sweep — gold / chrome / rose / bronze / rainbow', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.8, env:1 },
    { k:'shine',  label:'Shine', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'speed',  label:'Shine Speed', min:1, max:6, step:1, def:1, show:s=> s.shine>0 },
    { k:'angle',  label:'Shine Angle', min:0, max:345, step:15, def:45, show:s=> s.shine>0 },
    { k:'tone',   label:'Tone', type:'select', def:0, options:[[0,'Gold'],[1,'Silver / Chrome'],[2,'Rainbow'],[3,'Rose'],[4,'Bronze']] },
  ]},
  { id:'rainbow', name:'Colour Sweep', hint:'colour overlay — static gradient, travelling wave, or holographic foil (luma-modulated diffraction)', on:false, open:false, params:[
    { k:'amount',  label:'Amount', min:0, max:1, step:.01, def:.6, env:1, envd:1 },
    { k:'style',   label:'Style', type:'select', def:0, options:[[0,'Full Gradient'],[1,'Travelling Wave'],[2,'Foil (luma-modulated)']] },
    { k:'palette', label:'Palette', type:'select', def:2, options:[[2,'Rainbow'],[8,'Fire'],[9,'Candy'],[10,'Festive']] },
    { k:'bands',   label:'Bands', min:1, max:12, step:1, def:2, show:s=> (s.style|0)!==0 },
    { k:'width',   label:'Wave Width', min:0, max:1, step:.01, def:.5, show:s=> (s.style|0)===1 },
    { k:'sheen',   label:'Sheen', min:0, max:1, step:.01, def:.5, show:s=> (s.style|0)===2 },
    { k:'speed',   label:'Cycle / Scroll Speed', min:1, max:6, step:1, def:1 },
    { k:'angle',   label:'Angle', min:0, max:345, step:15, def:45 },
    { k:'blend',   label:'Blend', type:'select', def:0, options:[[0,'Overlay'],[1,'Screen'],[2,'Hue (recolor)'],[3,'Soft']] },
  ]},
  { id:'sparkle', name:'Sparkle', hint:'twinkling glitter — gold / white / rainbow stars', on:false, open:false, params:[
    { k:'amount',  label:'Amount', min:0, max:1, step:.01, def:.8, env:1 },
    { k:'density', label:'Density', min:0, max:1, step:.01, def:.4 },
    { k:'size',    label:'Size', min:0, max:1, step:.01, def:.4 },
    { k:'speed',   label:'Twinkle Speed', min:1, max:4, step:1, def:1 },
    { k:'shape',   label:'Shape', type:'select', def:0, options:[[0,'Star (4pt)'],[1,'Star (6pt)'],[2,'Sparkle (8pt)'],[3,'Dot'],[4,'Diamond'],[5,'Hexagon'],[6,'Star (5pt)'],[7,'Heart']] },
    { k:'tone',    label:'Tone', type:'select', def:0, options:[[0,'Gold'],[1,'White'],[2,'Rainbow'],[3,'Ice'],[4,'Pink'],[5,'Emerald'],[6,'Violet'],[8,'Fire'],[9,'Candy'],[10,'Festive'],[11,'Black (light bg)']] },
    { k:'motion',  label:'Motion', type:'select', def:1, options:[[0,'None (twinkle in place)'],[1,'Fall'],[2,'Rise'],[3,'Drift'],[4,'Explode']] },
    { k:'dist',    label:'Distance', min:0, max:1, step:.01, def:.3, show:s=> (s.motion|0)!==0 },
    { k:'angle',   label:'Drift Angle', min:0, max:345, step:15, def:0, show:s=> (s.motion|0)===3 },
    { k:'life',    label:'Life Pattern', type:'select', def:0, options:[[0,'Fade'],[1,'Shrink'],[2,'Burst'],[3,'Trail']], show:s=> (s.motion|0)!==0 },
  ]},
  { id:'burst', name:'Burst Lines', hint:'radial 集中線, or a soft spinning ARGB fan — pick a Style', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'style',  label:'Style', type:'select', def:0, options:[[0,'Speed Lines (集中線)'],[1,'Fan Blades (ARGB)']] },
    { k:'lines',  label:'Lines', min:0, max:1, step:.01, def:.5, show:s=> s.style!==1 },
    { k:'blades', label:'Blades', min:2, max:9, step:1, def:5, show:s=> s.style===1 },
    { k:'streak', label:'Streak', min:0, max:1, step:.01, def:.6, show:s=> s.style===1 },
    { k:'size',   label:'Size', min:0, max:1, step:.01, def:.5, show:s=> s.style===1 },
    { k:'jitter', label:'Width Jitter', min:0, max:1, step:.01, def:.6 },
    { k:'reach',  label:'Reach (to centre)', min:0, max:1, step:.01, def:.7, show:s=> s.style!==1 },
    { k:'spin',   label:'Spin (turns/loop)', min:-1, max:1, step:.05, def:.15 },
    { k:'tone',   label:'Tone', type:'select', def:0, options:[[0,'Gold'],[1,'White'],[2,'Rainbow'],[3,'Ice'],[4,'Pink'],[5,'Emerald'],[6,'Violet'],[7,'Ink (dark)'],[8,'Fire'],[9,'Candy'],[10,'Festive'],[11,'Black']] },
    { k:'blend',  label:'Blend', type:'select', def:0, options:[[0,'Screen'],[1,'Add'],[2,'Overlay'],[3,'Solid'],[4,'Multiply (dark)']] },
    { k:'cx',     label:'Hub X', min:0, max:1, step:.01, def:.5, show:s=> s.style===1 },
    { k:'cy',     label:'Hub Y', min:0, max:1, step:.01, def:.5, show:s=> s.style===1 },
  ]},
  { id:'edgeglow', name:'Edge Glow', hint:'ambient border bounce — colour bleeds in from the edges like indirect light, no source drawn', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.7, env:1, envd:1 },
    { k:'reach',  label:'Reach', min:0, max:1, step:.01, def:.35 },
    { k:'speed',  label:'Chase Speed (turns/loop)', min:-6, max:6, step:1, def:1 },
    { k:'tone',   label:'Tone', type:'select', def:2, options:[[0,'Gold'],[1,'White'],[2,'Rainbow'],[3,'Ice'],[4,'Pink'],[5,'Emerald'],[6,'Violet'],[8,'Fire'],[9,'Candy'],[10,'Festive']] },
    { k:'blend',  label:'Blend', type:'select', def:1, options:[[0,'Mix'],[1,'Screen'],[2,'Overlay'],[3,'Add']] },
  ]},
  // ---- Dream / Optics ----
  { id:'kaleido', name:'Kaleidoscope', hint:'mirror or rotate the frame into symmetric wedges', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'mode',   label:'Mode', type:'select', def:1, options:[[0,'Mirror (wedge)'],[1,'Rotate copies']] },
    { k:'seg',    label:'Segments', min:2, max:16, step:1, def:6 },
    { k:'spin',   label:'Spin (sectors/loop)', min:-6, max:6, step:1, def:1 },
    { k:'angle',  label:'Source Angle', min:0, max:345, step:15, def:0 },
    { k:'spread', label:'Fan Spread', min:0, max:1, step:.01, def:.35 },
    { k:'zoom',   label:'Zoom Out', min:0, max:1, step:.01, def:.3 },
    { k:'cx',     label:'Hub X', min:0, max:1, step:.01, def:.5 },
    { k:'cy',     label:'Hub Y', min:0, max:1, step:.01, def:.5 },
  ]},
  { id:'prism', name:'Soft Prism', hint:'smooth chromatic dispersion — glass / dream sheen', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'spread', label:'Spread', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'blur',   label:'Blur', min:0, max:1, step:.01, def:.3 },
    { k:'rot',    label:'Rotation (turns/loop)', min:0, max:4, step:1, def:1 },
  ]},
  { id:'starf', name:'Star Filter', hint:'cross-filter light rays streaming from highlights', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'thresh', label:'Threshold', min:0, max:1, step:.01, def:.6 },
    { k:'length', label:'Length', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'rays',   label:'Rays', type:'select', def:0, options:[[0,'4-point'],[1,'6-point'],[2,'8-point'],[3,'Anamorphic']] },
    { k:'angle',  label:'Angle', min:0, max:345, step:15, def:45 },
  ]},
  { id:'iris', name:'Iridescent Film', hint:'oil-slick / soap-bubble rainbow on edges & tones', on:false, open:false, params:[
    { k:'amount',    label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'angscale',  label:'Edge Hue', min:0, max:1, step:.01, def:.5 },
    { k:'lumascale', label:'Tone Hue', min:0, max:2, step:.01, def:1 },
    { k:'speed',     label:'Shift Speed', min:0, max:4, step:1, def:1 },
    { k:'edge',      label:'Apply To', type:'select', def:0, options:[[0,'All'],[1,'Edges only']] },
  ]},
  { id:'bokeh', name:'Bokeh Bloom', hint:'soft light discs bloom from the highlights', on:false, open:false, params:[
    { k:'amount',  label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'density', label:'Density', min:0, max:1, step:.01, def:.4 },
    { k:'size',    label:'Size', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'thresh',  label:'Threshold', min:0, max:1, step:.01, def:.6 },
    { k:'from',    label:'From', type:'select', def:0, options:[[0,'Highlights'],[1,'Saturated'],[2,'Any bright/vivid']] },
    { k:'shape',   label:'Shape', type:'select', def:0, options:[[0,'Circle'],[1,'Hexagon'],[2,'Star (5pt)'],[3,'Heart'],[4,'Diamond'],[5,'Star (4pt)'],[6,'Star (6pt)'],[7,'Sparkle (8pt)']] },
  ]},
  { id:'aura', name:'Aura', hint:'soft radial halo from a fixed anchor or from image highlights / saturated / any pixels — Bokeh-like sources, Edge-Glow-soft look', on:false, open:false, params:[
    { k:'amount',   label:'Amount', min:0, max:1, step:.01, def:.7, env:1 },
    { k:'mode',     label:'Mode', type:'select', def:0, options:[[0,'Ambient'],[1,'Bokeh'],[2,'Radiant']] },
    { k:'source',   label:'Source', type:'select', def:10, options:[[0,'Center'],[1,'Top'],[2,'Bottom'],[3,'Left'],[4,'Right'],[5,'Top-Left'],[6,'Top-Right'],[7,'Bottom-Left'],[8,'Bottom-Right'],[9,'Custom (X/Y)'],[10,'Image Highlights'],[11,'Image Saturated'],[12,'Image Any']] },
    { k:'x',        label:'X', min:0, max:1, step:.01, def:.5, show:s=> (s.source|0)===9 },
    { k:'y',        label:'Y', min:0, max:1, step:.01, def:.5, show:s=> (s.source|0)===9 },
    { k:'thresh',   label:'Threshold', min:0, max:1, step:.01, def:.5, show:s=> (s.source|0)>=10 },
    { k:'density',  label:'Density', min:0, max:1, step:.01, def:.5, show:s=> (s.source|0)>=10 },
    { k:'radius',   label:'Radius', min:.05, max:1, step:.01, def:.3 },
    { k:'core',     label:'Core Light', min:0, max:1, step:.01, def:.35 },
    { k:'soft',     label:'Softness', min:0, max:1, step:.01, def:.6 },
    { k:'rings',    label:'Rings', min:0, max:6, step:1, def:0 },
    { k:'flow',     label:'Ring Flow', min:0, max:4, step:1, def:1, show:s=> (s.rings|0)>0 },
    { k:'rays',     label:'Rays', min:0, max:24, step:1, def:0 },
    { k:'streak',   label:'Light Streak', min:0, max:1, step:.01, def:.18 },
    { k:'spin',     label:'Ray Spin', min:-2, max:2, step:.05, def:.15, show:s=> (s.rays|0)>0 },
    { k:'pulse',    label:'Pulse', min:0, max:1, step:.01, def:.3 },
    { k:'tone',     label:'Tone', type:'select', def:1, options:[[0,'Gold'],[1,'White'],[2,'Rainbow'],[3,'Ice'],[4,'Pink'],[5,'Emerald'],[6,'Violet'],[7,'Source color'],[8,'Fire'],[9,'Candy'],[10,'Festive'],[11,'Black (light bg)']] },
    { k:'blend',    label:'Blend', type:'select', def:1, options:[[0,'Overlay'],[1,'Screen'],[2,'Add (lighter)'],[3,'Soft']] },
  ]},
  { id:'liquid', name:'Liquid Glass', hint:'scattered water/glass droplets that lens the picture', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'amp',    label:'Refraction', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'count',  label:'Droplets', min:0, max:1, step:.01, def:.5 },
    { k:'size',   label:'Droplet Size', min:0, max:1, step:.01, def:.5 },
    { k:'chroma', label:'Chromatic Edge', min:0, max:1, step:.01, def:.3 },
  ]},
  { id:'paper', name:'Paper Cutout', hint:'posterized paper layers with drop shadows', on:false, open:false, params:[
    { k:'amount',  label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'levels',  label:'Layers', min:2, max:8, step:1, def:4 },
    { k:'depth',   label:'Shadow', min:0, max:1, step:.01, def:.5 },
    { k:'angle',   label:'Light Angle', min:0, max:345, step:15, def:135 },
    { k:'texture', label:'Paper Grain', min:0, max:1, step:.01, def:.2 },
  ]},
  { id:'halftone', name:'Halftone', hint:'dot-matrix / newsprint dots', on:false, open:false, params:[
    { k:'cell', label:'Cell Size', min:3, max:20, step:1, def:6 },
    { k:'shape', label:'Shape', type:'select', def:0, options:[[0,'Circle'],[1,'Square'],[2,'Triangle'],[3,'Hexagon'],[4,'Line'],[5,'CMYK Screen'],[6,'Packed Round']] },
    { k:'angle', label:'Grid Angle', min:-45, max:45, step:1, def:0 },
    { k:'bg',   label:'Background', type:'select', def:0, options:[[0,'Dark (LED)'],[1,'Light (print)'],[2,'None'],[3,'White LED'],[4,'Amber CRT'],[5,'Green Phosphor'],[6,'Blueprint'],[7,'Sepia'],[8,'Neon'],[9,'Riso']] },
    { k:'dotmode', label:'LED Pattern', type:'select', def:0, options:[[0,'Variable size'],[1,'Fixed size']] },
    { k:'invert', label:'Ink Mapping', type:'select', def:0, options:[[0,'Normal'],[1,'Invert'],[2,'Threshold'],[3,'Threshold Invert'],[4,'Mono']] },
    { k:'mix',  label:'Mix', min:0, max:1, step:.01, def:1, env:1 },
    { k:'fade',  label:'Fade', type:'select', def:0,
      options:[[0,'Even'],[1,'Right'],[2,'Left'],[3,'Bottom'],[4,'Top'],[5,'Bright areas'],[6,'Dark areas']] },
    { k:'cover', label:'Coverage', min:0, max:1, step:.01, def:.5, env:1, show:s=> s.fade!==0 },
  ]},
  { id:'crt', name:'CRT', hint:'tube curve · RGB phosphor mask · scanlines · convergence · glow', on:false, open:false, params:[
    { k:'amount',   label:'Curvature',     min:0, max:1, step:.01, def:.3 },
    { k:'round',    label:'Screen Bulge',  min:0, max:1, step:.01, def:.2 },
    { k:'corner',   label:'Corner Dark',   min:0, max:1, step:.01, def:.5 },
    { k:'frame',    label:'Bezel',         min:0, max:1, step:.01, def:.08 },
    { k:'mask',     label:'Phosphor', type:'select', def:1,
      options:[[0,'None'],[1,'Aperture Grille'],[2,'Shadow Mask'],[3,'Slot Mask']] },
    { k:'phosphor', label:'Mask Depth',    min:0, max:1, step:.01, def:.5, env:1 },
    { k:'scan',     label:'Scanlines',     min:0, max:1, step:.01, def:.4 },
    { k:'converge', label:'Convergence',   min:0, max:1, step:.01, def:.25, env:1 },
    { k:'glow',     label:'Phosphor Glow', min:0, max:1, step:.01, def:.3, env:1 },
  ]},
  { id:'sync', name:'Signal / Sync', hint:'horizontal-sync instability — diagonal skew · flagging · bad contact', on:false, open:false, params:[
    { k:'hsync',   label:'H-Sync',      min:-1, max:1, step:.01, def:0 },
    { k:'flag',    label:'Flagging',    min:0, max:1, step:.01, def:0, env:1 },
    { k:'contact', label:'Bad Contact', min:0, max:1, step:.01, def:0, env:1 },
  ]},
  { id:'ghost', name:'Ghosting', hint:'multipath echo — faint offset duplicate(s), can drift over the loop', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'offset', label:'Offset', min:2, max:80, step:1, def:22 },
    { k:'echoes', label:'Echoes', min:1, max:3, step:1, def:2 },
    { k:'pre',    label:'Pre-echo', min:0, max:1, step:.01, def:.3 },
    { k:'drift',  label:'Drift', min:0, max:1, step:.01, def:0 },
    { k:'rate',   label:'Drift Rate', min:1, max:4, step:1, def:1 },
  ]},
  { id:'dotcrawl', name:'Dot Crawl', hint:'composite cross-colour — rainbow shimmer on vertical edges', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.6, env:1 },
    { k:'size',   label:'Dot Size', min:1, max:5, step:1, def:2 },
    { k:'speed',  label:'Crawl', min:1, max:12, step:1, def:6 },
  ]},
  { id:'hum', name:'Hum Bar', hint:'mains-hum brightness band rolling up the screen', on:false, open:false, params:[
    { k:'amount', label:'Darkness', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'width',  label:'Band Width', min:0, max:1, step:.01, def:.4 },
    { k:'speed',  label:'Roll Speed', min:1, max:8, step:1, def:2 },
  ]},
  { id:'herring', name:'Herringbone', hint:'RF interference — moving diagonal weave', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'freq',   label:'Density', min:1, max:10, step:1, def:5 },
    { k:'speed',  label:'Drift', min:1, max:8, step:1, def:2 },
  ]},
  { id:'feedback', name:'Feedback Zoom', hint:'droste tunnel — nested copies that flow over the loop', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'zoom',   label:'Zoom (under 1 = nested)', min:.6, max:1.4, step:.01, def:.82 },
    { k:'copies', label:'Copies', min:2, max:8, step:1, def:5 },
    { k:'feather',label:'Edge Feather', min:0, max:1, step:.01, def:.35 },
    { k:'flow',   label:'Flow (steps/loop)', min:-3, max:3, step:1, def:1 },
    { k:'rotate', label:'Twist (° per step → slow spin)', min:-45, max:45, step:.5, def:8 },
    { k:'speed',  label:'Fast Spin (whole turns/loop)', min:-1, max:1, step:1, def:0 },
    { k:'pulse',  label:'Zoom Pulse', min:0, max:1, step:.01, def:0 },
  ]},
  { id:'extrude', name:'Extrude', hint:'pick a band of the picture (tone / colour / edges) and push it out — angle or radial, plain or colour-tinted, pseudo-3D', on:false, open:false, params:[
    { k:'key',    label:'Select By', type:'select', def:0, options:[[0,'Lightness'],[1,'Saturation'],[2,'Hue'],[3,'Edges']] },
    { k:'center', label:'Range Centre', min:0, max:1, step:.01, def:.78, show:s=> s.key!==3 },
    { k:'width',  label:'Range Width', min:.01, max:1, step:.01, def:.22, show:s=> s.key!==3 },
    { k:'thresh', label:'Edge Threshold', min:0, max:1, step:.01, def:.18, show:s=> s.key===3 },
    { k:'mode',   label:'Push Mode', type:'select', def:0, options:[[0,'Angle'],[1,'Radial (from point)']] },
    { k:'angle',  label:'Direction', min:0, max:345, step:15, def:45, show:s=> s.mode!==1 },
    { k:'cx',     label:'Radial X', min:0, max:1, step:.01, def:.5, show:s=> s.mode===1 },
    { k:'cy',     label:'Radial Y', min:0, max:1, step:.01, def:.5, show:s=> s.mode===1 },
    { k:'invert', label:'Radial Direction', type:'select', def:0, options:[[0,'Outward'],[1,'Inward']], show:s=> s.mode===1 },
    { k:'dist',   label:'Distance', min:0, max:1, step:.01, def:.3, env:1, envd:1 },
    { k:'shade',  label:'Shade (depth falloff)', min:-1, max:1, step:.01, def:.65 },
    { k:'tint',   label:'Tint', type:'select', def:0, options:[[0,'Original'],[1,'Black'],[2,'White'],[3,'Gold'],[4,'Red'],[5,'Rainbow'],[6,'Fire'],[7,'Candy'],[8,'Festive']] },
    { k:'tmix',   label:'Tint Amount', min:0, max:1, step:.01, def:.7, show:s=> s.tint!==0 },
    { k:'bmode',  label:'Side Blend', type:'select', def:0, options:[[0,'Replace'],[1,'Screen'],[2,'Multiply'],[3,'Add'],[4,'Overlay']] },
    { k:'opacity',label:'Side Opacity', min:0, max:1, step:.01, def:1 },
  ]},
  { id:'melt', name:'Melt', hint:'pixel drip (breathes over the loop) — Drip or vertical Wrap', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.4, env:1 },
    { k:'mode',   label:'Mode', type:'select', def:0, options:[[0,'Drip'],[1,'Wrap']] },
    { k:'width',  label:'Drip Width', min:1, max:16, step:1, def:1 },
    { k:'spread', label:'Spread', min:0, max:1, step:.01, def:.5 },
    { k:'curve',  label:'Curve', type:'select', def:1,
      options:[[1,'Peak'],[2,'Pulse'],[3,'Build → Drop'],[4,'Stutter'],[5,'Swell'],[6,'Drop → Build'],[7,'Bounce'],[8,'Wander']] },
    { k:'rate',   label:'Rate', min:1, max:8, step:1, def:2, show:s=> [2,4,7,8].includes(s.curve|0) },
  ]},
  { id:'emboss', name:'Emboss', hint:'directional relief — carved / raised metal look', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.7, env:1 },
    { k:'angle',  label:'Light angle', min:0, max:360, step:15, def:135 },
    { k:'mix',    label:'Keep colour', min:0, max:1, step:.01, def:0 },
  ]},
  { id:'posterize', name:'Posterize', hint:'reduce colours — banding / retro (optional dither)', on:false, open:false, params:[
    { k:'levels', label:'Levels', min:2, max:12, step:1, def:5 },
    { k:'dither', label:'Dither', min:0, max:1, step:.01, def:0 },
  ]},
  { id:'duotone', name:'Duotone', hint:'map brightness to a 2-colour gradient', on:false, open:false, params:[
    { k:'preset', label:'Palette', type:'select', def:0,
      options:[[0,'Teal / Peach'],[1,'Blue / Orange'],[2,'Purple / Yellow'],[3,'Magenta / Cyan'],[4,'Green / Pink'],[5,'Mono']] },
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.85, env:1 },
  ]},
  { id:'solarize', name:'Solarize', hint:'invert tones past a threshold (Sabattier)', on:false, open:false, params:[
    { k:'threshold', label:'Threshold', min:0, max:1, step:.01, def:.55 },
    { k:'amount',    label:'Amount', min:0, max:1, step:.01, def:.8, env:1 },
  ]},
  { id:'zoom', name:'Zoom', hint:'enlarge / overscan (also hides wobble wrap seams)', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.3, env:1 },
  ]},
  { id:'mask', name:'Region Mask', hint:'confine effects to a rectangle — fixed / roaming / invertable', on:false, open:false, params:[
    { k:'source',   label:'Mask Source', type:'select', def:0, options:[[0,'Rectangle'],[6,'Roaming Rectangle'],[1,'Shadows'],[2,'Midtones'],[3,'Highlights'],[4,'Edges'],[5,'Noise']] },
    { k:'threshold',label:'Threshold', min:0, max:1, step:.01, def:.5, show:s=> s.source!==0 && s.source!==6 },
    { k:'mode',     label:'Mode', type:'select', def:0, options:[[0,'Fixed'],[1,'Roam']], show:()=>false },  // legacy: kept so old links still decode
    { k:'x0',       label:'X start %', min:0, max:100, step:1, def:20, show:s=> s.source===0 },
    { k:'x1',       label:'X end %',   min:0, max:100, step:1, def:80, show:s=> s.source===0 },
    { k:'y0',       label:'Y start %', min:0, max:100, step:1, def:20, show:s=> s.source===0 },
    { k:'y1',       label:'Y end %',   min:0, max:100, step:1, def:80, show:s=> s.source===0 },
    { k:'invert',   label:'Invert', type:'select', def:0, options:[[0,'Effects inside'],[1,'Effects outside']] },
    { k:'interval', label:'Roam Steps', min:1, max:16, step:1, def:4, show:s=> s.source===5 || s.source===6 },
    { k:'feather',  label:'Feather', min:0, max:1, step:.01, def:.08 },
  ]},
  { id:'time', name:'Time', hint:'frame drop · stutter · trails — acts on the footage, not the frame', on:false, open:false, params:[
    // every hold divides the loop's 90 frames, so the last group is full length and the loop closes.
    // Stops at 10 (3fps): past that so few frames are left that it reads as a still, not a stutter.
    { k:'hold',   label:'Frame Hold', type:'select', def:1,
      options:[[1,'Off'],[2,'2 frames'],[3,'3'],[5,'5'],[6,'6'],[9,'9'],[10,'10']] },
    { k:'drop',   label:'Random Drop', min:0, max:.9, step:.01, def:0, env:1 },
    { k:'trail',  label:'Trails', min:0, max:1, step:.01, def:0, env:1 },
    // Reach, not count, is what makes a trail visible: neighbouring frames are 1/30s apart and
    // nearly identical, so averaging them just gives the picture back. Gap sets how far apart the
    // blended frames sit — 1 is a motion blur, high is separated echoes.
    { k:'gap',    label:'Trail Gap (frames)', min:1, max:12, step:1, def:5, show:s=> s.trail>0 },
    { k:'trailn', label:'Trail Frames (a render each)', min:2, max:4, step:1, def:3, show:s=> s.trail>0 },
  ]},
  { id:'stale', name:'Stale Blocks', hint:'a starved stream — blocks stuck on an older frame', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:.5, env:1 },
    { k:'block',  label:'Block Size', min:8, max:48, step:4, def:16 },
    { k:'age',    label:'Max Age (frames)', min:1, max:12, step:1, def:6, show:s=> (s.gop|0)===0 },
    { k:'steps',  label:'Age Steps (a render each)', min:1, max:3, step:1, def:2 },
    { k:'gop',    label:'Keyframe (GOP, frames)', min:0, max:45, step:1, def:0 },
    { k:'rate',   label:'Re-roll Rate (per loop)', min:1, max:30, step:1, def:6, show:s=> (s.gop|0)===0 },
  ]},
  { id:'synctear', name:'Sync Tear', hint:'horizontal hold failure — the picture steps sideways at the tear', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'tears',  label:'Tears', min:1, max:6, step:1, def:3 },
    { k:'shift',  label:'Slip (px)', min:0, max:64, step:2, def:36 },
    { k:'delay',  label:'Lag (frames)', min:0, max:12, step:1, def:3 },
    { k:'rate',   label:'Re-tear Rate (per loop)', min:1, max:12, step:1, def:6 },
    { k:'edge',   label:'Edge', type:'select', def:0, options:[[0,'Hard'],[3,'Round'],[1,'Ramp'],[2,'Overshoot']] },
    { k:'edgew',  label:'Edge (px)', min:2, max:40, step:1, def:14, show:s=> (s.edge|0)!==0 },
  ]},
  { id:'playback', name:'Playback', hint:'reorder the frames — ping-pong / reverse / stutter / jitter', on:false, open:false, params:[
    { k:'order',  label:'Order', type:'select', def:1,
      options:[[1,'Ping-Pong'],[2,'Reverse Burst'],[3,'Stutter Loop'],[4,'Jitter']] },
    { k:'olen',   label:'Segment (frames)', min:2, max:30, step:1, def:8, show:s=> [1,2,3].includes(s.order|0) },
  ]},
  { id:'chroma', name:'Chroma Persistence', hint:'the colour lags behind the picture — drips off moving edges', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'delay',  label:'Lag (frames)', min:1, max:12, step:1, def:4 },
    { k:'mode',   label:'What Lags', type:'select', def:0, options:[[0,'Colour (crisp shape)'],[1,'Brightness (double exposure)']] },
  ]},
  { id:'interlace', name:'Interlace', hint:'two fields scanned a moment apart — combing on anything that moved', on:false, open:false, params:[
    { k:'amount', label:'Amount', min:0, max:1, step:.01, def:1, env:1 },
    { k:'delay',  label:'Field Delay (frames)', min:1, max:12, step:1, def:2 },
    { k:'thick',  label:'Field Height (lines)', min:1, max:8, step:1, def:1 },
    { k:'swap',   label:'Field Order', type:'select', def:0, options:[[0,'Odd lines lag'],[1,'Even lines lag']] },
  ]},
  { id:'motion', name:'Envelope', hint:'makes destruction breathe over the loop (pick targets via ⓔ)', on:false, open:false, params:[
    { k:'mode', label:'Curve', type:'select', def:1,
      options:[[0,'Constant'],[1,'Peak (crash mid)'],[2,'Pulse'],[3,'Build → Drop'],[4,'Stutter'],[5,'Swell'],[6,'Drop → Build'],[7,'Bounce'],[8,'Wander'],[9,'Burst']] },
    { k:'depth', label:'Depth', min:0, max:1, step:.01, def:.7 },
    { k:'rate',  label:'Rate / Count', min:1, max:12, step:1, def:3, show:s=> [2,4,7,8,9].includes(s.mode|0) },
  ]},
];

// effect cards are shown grouped by sub-genre (order here = display order)
const FX_GROUPS = [
  ['File Corruption',       ['jpeg','png','webp','gifg','audio','sonify','byteshift','bitplane']],   // real encoded-byte damage + raw reinterpret
  ['Digital Glitch',        ['glitch','mosh','compress','dct','pixsort','databend','bmpmisread','wrongfmt','rle','gif','pixelate']],
  ['Analog Signal',         ['vhs','sync','roll','noise','ghost','dotcrawl','hum','herring','degauss']],
  ['Film / Display',        ['film','crt','hud','halftone']],
  ['Light / Optics',        ['bloom','leak','aura','sparkle','burst','prism','iris','starf','bokeh','edgeglow']],
  ['Distortion / Geometry', ['warp','melt','extrude','feedback','kaleido','liquid']],
  ['Colour / Material',     ['color','duotone','solarize','posterize','emboss','gold','rainbow','paper']],
  ['Video',                 ['time','playback','stale','synctear','interlace','chroma']],        // acts on the footage, not any one frame
  ['Global',                ['zoom','mask','motion']],                                           // whole-frame settings → lives in its own panel
];

const PRESETS = {
  // ---- Classic ----
  'VHS Tape':    { vhs:{on:1,aberration:8,scanline:.45,bleed:4,tracking:.4,wobble:7,wobmode:1}, glitch:{on:0}, noise:{on:1,grain:.22,flicker:.15}, color:{on:1,saturate:1.1,contrast:1.05,hue:0,tint:.15,vignette:.4} },
  '8mm Film':    { vhs:{on:1,aberration:0,scanline:0,bleed:0,tracking:0,wobble:1,wobmode:2}, glitch:{on:0}, noise:{on:1,grain:.14,flicker:.2}, color:{on:1,saturate:.8,contrast:1.1,bright:1.08,hue:0,tint:.1,vignette:.5}, film:{on:1,dust:.6,scratch:.5,sepia:.6,burn:.4}, roll:{on:0}, mosh:{on:0}, leak:{on:1,amount:.4,tone:0,pos:4,size:.6,drift:.5} },
  'CRT':         { vhs:{on:1,aberration:5,scanline:0,bleed:2,tracking:.1,wobble:1}, glitch:{on:0}, noise:{on:1,grain:.1,flicker:.08}, color:{on:1,saturate:1.2,contrast:1.1,hue:0,tint:.05,vignette:.35}, crt:{on:1,amount:0.25,round:.5,corner:.5,frame:.08,mask:2,phosphor:.5,scan:.5,converge:.3,glow:.35}, bloom:{on:1,amount:.3,size:8,glow:.2}, sync:{on:1,hsync:0,flag:0.15,contact:0.12} },
  'Backrooms':   { vhs:{on:1,aberration:4,scanline:.28,bleed:2,tracking:.22,wobble:2}, glitch:{on:0}, noise:{on:1,grain:.2,flicker:.14}, color:{on:1,saturate:.85,contrast:1.12,hue:12,tint:.4,vignette:.55}, hum:{on:1,amount:.45,width:.5,speed:1} },
  'Broken TV':   { vhs:{on:1,aberration:6,scanline:0,bleed:2,tracking:.9,wobble:8}, glitch:{on:1,amount:.2,slices:18,shift:20,rgb:5}, noise:{on:1,grain:.35,flicker:.3}, color:{on:1,saturate:.7,contrast:1.15,hue:0,tint:0,vignette:.45}, roll:{on:1,hspeed:0,hstep:0,vspeed:1.1,band:.6,ease:4}, crt:{on:1,amount:0.46,round:.45,corner:.5,frame:.07,mask:2,phosphor:.45,scan:.4,converge:.4,glow:.3}, sync:{on:1,hsync:0,flag:0.45,contact:0.5}, synctear:{on:1,amount:.55,tears:3,shift:26,delay:2,rate:5,edge:0}, interlace:{on:1,amount:.7,delay:2,thick:1,swap:0}, motion:{on:1,mode:4,depth:.6,rate:6} },
  // ---- Glitch ----
  'Digital Decay':{ glitch:{on:1,amount:.45,slices:22,shift:30,rgb:10}, compress:{on:1,amount:.5,chroma:.5,ring:.6,block:8}, databend:{on:1,amount:.6,skew:.5,scramble:.35,speed:2}, synctear:{on:1,amount:.5,tears:4,shift:30,delay:2,rate:6,edge:0} },
  'Datamosh':    { mosh:{on:1,intensity:.75,blocks:.65,bloom:3,sort:.55,chaos:.2,rate:12}, motion:{on:1,mode:1,depth:.6,rate:3}, playback:{on:1,order:1,olen:8} },
  // a starved low-framerate stream: a slow Warp gives the temporal effects something to break, then
  // blocks freeze (Stale), the picture macroblocks (Compression), colour lags (Chroma) and it stutters (Time)
  'Dead Stream': { compress:{on:1,amount:.38,chroma:.17,ring:.3,soft:.45,block:16}, ghost:{on:1,amount:.12,offset:22,echoes:2,pre:.3,drift:0,rate:1}, melt:{on:1,amount:.07,mode:0,width:1,spread:.5,curve:4,rate:2}, stale:{on:1,amount:.6,block:16,age:6,steps:2,gop:30,rate:4}, chroma:{on:1,amount:.7,delay:5,mode:0} },
  // temporal (Video) showcases — each carries its own frame motion (roll / warp) so the effects bite
  'JPEG Glitch':{ vhs:{on:0}, glitch:{on:0}, noise:{on:1,grain:.06,flicker:.05}, color:{on:0}, roll:{on:0}, film:{on:0}, mosh:{on:0}, jpeg:{on:1,amount:.35,quality:.3,frames:8,_seq:[0,0,1,1,0,1,1,1]}, png:{on:0} },
  'PNG Glitch':  { vhs:{on:0}, glitch:{on:0}, noise:{on:0}, color:{on:0}, roll:{on:0}, film:{on:0}, mosh:{on:0}, jpeg:{on:0}, png:{on:1,amount:.3,noise:.15,dir:0,frames:8,_seq:[0,0,1,1,0,1,1,1]} },
  'Roll Break':  { noise:{on:1,grain:.15,flicker:.12}, color:{on:1,saturate:1.0,contrast:1.08,hue:0,tint:0,vignette:.3}, roll:{on:1,hspeed:.3,hstep:0,vspeed:1.2,band:.75,ease:0}, synctear:{on:1,amount:.5,tears:3,shift:26,delay:2,rate:5,edge:0}, playback:{on:1,order:2,olen:8} },
  // ---- Horror ----
  'Cursed Tape': { vhs:{on:1,aberration:10,scanline:.5,bleed:3,tracking:.85,wobble:9}, noise:{on:1,grain:.4,flicker:.45}, color:{on:1,saturate:.55,contrast:1.35,hue:-25,tint:-.2,vignette:.75}, film:{on:1,dust:.35,scratch:.35,sepia:0,burn:.35}, roll:{on:1,hspeed:0,hstep:0,vspeed:.15,band:.4}, iris:{on:1,amount:.4,angscale:.6,lumascale:1,speed:1,edge:1}, chroma:{on:1,amount:.6,delay:5,mode:0}, motion:{on:1,mode:4,depth:.7,rate:5} },
  'Haunted Film':{ vhs:{on:1,aberration:0,scanline:0,bleed:0,tracking:0,wobble:3,wobmode:2}, glitch:{on:0}, noise:{on:1,grain:.35,flicker:.5}, color:{on:1,saturate:.4,contrast:1.3,hue:15,tint:.15,vignette:.8}, film:{on:1,dust:.8,scratch:.7,sepia:.55,burn:.7}, ghost:{on:1,amount:.5,offset:34,echoes:2,pre:.5,drift:.4,rate:1}, motion:{on:1,mode:2,depth:.6,rate:4} },
  'Red Room':    { vhs:{on:1,aberration:7,scanline:.35,bleed:2,tracking:.4,wobble:3}, noise:{on:1,grain:.25,flicker:.55}, color:{on:1,saturate:1.3,contrast:1.4,hue:-120,tint:.1,vignette:.7}, leak:{on:1,amount:.5,tone:2,pos:4,size:.7,drift:.4}, bloom:{on:1,amount:.4,size:14,glow:.45}, motion:{on:1,mode:2,depth:.7,rate:6}, synctear:{on:1,amount:.5,tears:3,shift:26,delay:2,rate:5,edge:0}, chroma:{on:1,amount:.5,delay:4,mode:0} },
  'Meltdown':    { vhs:{on:1,aberration:6,scanline:.2,bleed:2,tracking:.25,wobble:3}, glitch:{on:0}, noise:{on:1,grain:.15,flicker:.15}, color:{on:1,saturate:.7,contrast:1.2,hue:-30,tint:-.1,vignette:.6}, melt:{on:1,amount:.55,mode:0,width:3,spread:.5,curve:5,rate:2}, chroma:{on:1,amount:.5,delay:4,mode:1}, motion:{on:1,mode:1,depth:.6,rate:2} },
  // ---- Vivid ----
  'Y2K':         { vhs:{on:1,aberration:6,scanline:0,bleed:4,tracking:.05,wobble:0}, noise:{on:1,grain:.1,flicker:.05}, color:{on:1,saturate:1.3,contrast:1.2,hue:0,tint:0,vignette:.2}, dotcrawl:{on:1,amount:.5,size:2,speed:6}, pixelate:{on:1,size:5,mix:.6,fade:3,cover:.3}, sparkle:{on:1,amount:.6,density:.3,size:.35,speed:1,shape:0,tone:1} },
  'Neon':        { vhs:{on:1,aberration:12,scanline:.2,bleed:3,tracking:.1,wobble:2}, glitch:{on:0}, noise:{on:1,grain:.08,flicker:.05}, color:{on:1,saturate:1.9,contrast:1.25,bright:.95,hue:60,tint:-.2,vignette:.55}, bloom:{on:1,amount:.55,size:14,glow:.3}, starf:{on:1,amount:.5,thresh:.65,length:.4,rays:0,angle:45}, bokeh:{on:1,amount:.45,density:.35,size:.6,thresh:.6,from:0,shape:0} },
  'Vaporwave':   { vhs:{on:1,aberration:11,scanline:.18,bleed:5,tracking:.1,wobble:3}, glitch:{on:0}, noise:{on:1,grain:.07,flicker:.04}, color:{on:1,saturate:1.7,contrast:1.0,hue:-35,tint:-.15,vignette:.4}, film:{on:0}, roll:{on:0}, mosh:{on:0}, bloom:{on:1,amount:.4,size:12,glow:.5}, leak:{on:1,amount:.3,tone:4,pos:1,size:.6,drift:.4} },
  // ---- Camera / Scene ----
  'Security Cam':{ vhs:{on:1,aberration:3,scanline:.35,bleed:1,tracking:.15,wobble:1}, glitch:{on:0}, noise:{on:1,grain:.28,flicker:.1}, color:{on:1,saturate:.5,contrast:1.15,hue:-15,tint:-.05,vignette:.6}, hum:{on:1,amount:.4,width:.45,speed:1}, hud:{on:1,layout:4,size:1,opacity:.85} },
  'Fisheye Cam': { vhs:{on:1,aberration:3,scanline:.3,bleed:1,tracking:.15,wobble:1}, glitch:{on:0}, noise:{on:1,grain:.22,flicker:.1}, color:{on:1,saturate:.6,contrast:1.15,hue:-10,tint:-.05,vignette:.4}, crt:{on:1,amount:1,round:1,corner:1,frame:.1,mask:0,phosphor:0,scan:0,converge:0,glow:0}, hud:{on:1,layout:4,color:2,size:.9,opacity:.85} },
  'Bad Reception':{ vhs:{on:1,aberration:6,scanline:0,bleed:2,tracking:.3,wobble:3}, noise:{on:1,grain:.4,size:.55,type:1,flicker:.2,grain_env:0,flicker_env:0}, ghost:{on:1,amount:.6,offset:26,echoes:2,pre:.4,drift:0,rate:1,amount_env:1}, herring:{on:1,amount:.5,freq:7,speed:3}, hum:{on:1,amount:.3,width:.4,speed:2}, degauss:{on:1,amount:.3,sway:.35,freq:3,color:.35,curve:1,rate:2,_seq:[1,0,0,0,0,1,0,0]}, crt:{on:1,amount:0.42,round:.35,corner:.5,frame:.08,mask:1,phosphor:.4,scan:.35,converge:.3,glow:.3}, sync:{on:1,hsync:0,flag:0.25,contact:0.2}, motion:{on:1,mode:1,depth:.5,rate:3} },
  'Retro Game':  { vhs:{on:1,aberration:3,scanline:.4,bleed:0,tracking:0,wobble:0}, glitch:{on:0}, noise:{on:1,grain:.04,flicker:.16}, color:{on:1,saturate:1.5,contrast:1.15,hue:0,tint:0,vignette:.3}, film:{on:0}, roll:{on:0}, mosh:{on:0}, pixelate:{on:1,size:7}, hud:{on:0}, motion:{on:1,mode:2,depth:.5,rate:3} },
  'Underwater':  { vhs:{on:1,aberration:6,scanline:.1,bleed:4,tracking:.1,wobble:2}, glitch:{on:0}, noise:{on:1,grain:.08,flicker:.05}, color:{on:1,saturate:1.2,contrast:1.0,hue:120,tint:-.2,vignette:.5}, warp:{on:1,amp:2.25,freq:5,speed:2}, liquid:{on:1,amount:1,amp:.5,count:.55,size:.55,chroma:.3}, degauss:{on:1,amount:.16,sway:.85,freq:2,color:.12,curve:0,rate:2} },
  // ---- Lens / FX ----
  'Trip':        { vhs:{on:1,aberration:8,scanline:.1,bleed:4,tracking:.1,wobble:3}, glitch:{on:0}, noise:{on:1,grain:.05,flicker:.04}, color:{on:1,saturate:1.6,contrast:1.05,hue:90,tint:0,vignette:.35}, warp:{on:1,amp:5,freq:6,speed:2}, rainbow:{on:1,amount:.5,speed:2,angle:45,blend:2}, feedback:{on:1,amount:.4,zoom:.88,copies:5,feather:.4,flow:1,rotate:12,speed:0,pulse:.4}, playback:{on:1,order:1,olen:8}, bloom:{on:1,amount:.45,size:10,glow:.3}, motion:{on:1,mode:2,depth:.6,rate:3} },
  'Newsprint':   { vhs:{on:0}, glitch:{on:0}, noise:{on:1,grain:.1,flicker:.05}, color:{on:1,saturate:.9,contrast:1.2,hue:0,tint:.05,vignette:.3}, halftone:{on:1,cell:6,bg:1} },
  'Heat Haze':   { vhs:{on:1,aberration:5,scanline:.1,bleed:3,tracking:.1,wobble:2,wobmode:0}, noise:{on:1,grain:.07,size:0,type:0,flicker:.05}, color:{on:1,saturate:1.15,contrast:1.05,bright:1.08,hue:15,tint:.25,vignette:.4}, databend:{on:1,amount:.41,skew:.4,scramble:.4,speed:2}, warp:{on:1,amp:1.75,freq:5,speed:4,warpmode:0}, bloom:{on:1,amount:.35,size:14,glow:.55}, leak:{on:1,amount:.45,tone:0,pos:2,size:.6,drift:.6}, gold:{on:1,amount:.08,shine:.33,speed:2,angle:270,tone:2}, ghost:{on:1,amount:.16,offset:22,echoes:2,pre:.3,drift:0,rate:1} },
  'Wormhole':    { noise:{on:1,grain:.06,size:0,type:0,flicker:.03}, burst:{on:1,amount:.17,lines:0,jitter:.16,reach:0,spin:.45,tone:1,blend:0}, feedback:{on:1,amount:.95,zoom:1.09,copies:7,feather:.28,flow:3,rotate:18,speed:1,pulse:.71}, time:{on:1,hold:1,drop:.19,trail:0,gap:5,trailn:3} },
  'Sunwashed':   { vhs:{on:1,aberration:5,scanline:.08,bleed:3,tracking:.1,wobble:1}, noise:{on:1,grain:.06,flicker:.03}, color:{on:1,saturate:1.15,contrast:1.0,bright:1.28,hue:0,tint:.18,vignette:.12}, bloom:{on:1,amount:.5,size:12,glow:.6}, leak:{on:1,amount:.55,tone:1,pos:1,size:.6,drift:.4} },
  // ---- Art ----
  'Teal & Peach':{ vhs:{on:0}, glitch:{on:0}, noise:{on:1,grain:.05,flicker:.02}, color:{on:1,saturate:1.0,contrast:1.1,hue:0,tint:0,vignette:.45}, bloom:{on:1,amount:.3,size:8,glow:.3}, duotone:{on:1,preset:0,amount:.7}, leak:{on:1,amount:.3,tone:0,pos:0,size:.7,drift:.3} },
  'Acid':        { vhs:{on:1,aberration:6,scanline:.1,bleed:2,tracking:.1,wobble:2}, glitch:{on:1,amount:.22,slices:16,shift:20,rgb:8}, noise:{on:1,grain:.06,flicker:.05}, color:{on:1,saturate:1.5,contrast:1.1,hue:40,tint:0,vignette:.3}, solarize:{on:1,threshold:.5,amount:.85}, iris:{on:1,amount:.5,angscale:.6,lumascale:1.3,speed:2,edge:0} },
  'Risograph':   { vhs:{on:0}, glitch:{on:0}, noise:{on:1,grain:.12,flicker:.03}, color:{on:1,saturate:1.1,contrast:1.15,hue:0,tint:0,vignette:.35}, posterize:{on:1,levels:4,dither:.6}, duotone:{on:1,preset:1,amount:.55} },
  'Metal':       { vhs:{on:0}, glitch:{on:0}, noise:{on:1,grain:.04,flicker:.02}, color:{on:1,saturate:.7,contrast:1.35,hue:0,tint:0,vignette:.4}, emboss:{on:1,amount:.7,angle:135,mix:.3}, gold:{on:1,amount:.7,shine:.6,speed:1,angle:45,tone:1} },
  'Papercraft':  { vhs:{on:0}, noise:{on:1,grain:.03,flicker:.01}, color:{on:1,saturate:1.15,contrast:1.05,bright:1.05,hue:0,tint:.05,vignette:.2}, paper:{on:1,amount:1,levels:5,depth:.55,angle:135,texture:.25} },
  // ---- Hype (dopamine) ----
  'Jackpot':     { color:{on:1,saturate:1.25,contrast:1.12,bright:1.05,hue:0,tint:.08,vignette:.18}, gold:{on:1,amount:.9,shine:.8,speed:2,angle:45,tone:0}, burst:{on:1,amount:.6,lines:.6,reach:.7,spin:.15,tone:0,blend:0}, sparkle:{on:1,amount:.95,density:.7,size:.5,speed:2,shape:4,tone:0}, bloom:{on:1,amount:.35,size:10,glow:.3} },
  'Gold Rush':   { color:{on:1,saturate:1.2,contrast:1.15,bright:1.03,hue:0,tint:.1,vignette:.15}, gold:{on:1,amount:1,shine:.95,speed:3,angle:45,tone:0}, bloom:{on:1,amount:.4,size:14,glow:.45}, leak:{on:1,amount:.4,tone:1,pos:1,size:.7,drift:.4} },
  'Fever':       { vhs:{on:1,aberration:8,scanline:.1,bleed:3,tracking:.1,wobble:2}, color:{on:1,saturate:1.6,contrast:1.1,bright:1.05,hue:0,tint:0,vignette:.15}, rainbow:{on:1,amount:.65,speed:3,angle:45,blend:2}, burst:{on:1,amount:.7,lines:.6,reach:.8,spin:.35,tone:2,blend:0}, sparkle:{on:1,amount:.9,density:.6,size:.4,speed:2,tone:2}, bloom:{on:1,amount:.4,size:10,glow:.3} },
  // ---- Dream / Optics ----
  // ---- Reset ----
  'Clean':       { vhs:{on:0}, glitch:{on:0}, noise:{on:0}, color:{on:0} },
};
// select layout (group label → preset names)
const PRESET_GROUPS = [
  ['Analog / Camera',      ['VHS Tape','8mm Film','CRT','Security Cam','Bad Reception','Broken TV','Roll Break']],
  ['Digital Glitch',       ['Digital Decay','Datamosh','Dead Stream','JPEG Glitch','PNG Glitch']],
  ['Horror',               ['Cursed Tape','Haunted Film','Red Room','Meltdown','Backrooms']],
  ['Vivid / Hype',         ['Jackpot','Gold Rush','Fever','Y2K','Neon','Vaporwave']],
  ['Psychedelic / Spatial',['Trip','Wormhole','Heat Haze','Underwater','Fisheye Cam','Acid']],
  ['Print / Material',     ['Newsprint','Risograph','Papercraft','Metal','Retro Game']],
  ['Photo / Grade',        ['Sunwashed','Teal & Peach']],
];

// duotone palettes: [shadow rgb, highlight rgb]
const DUO_PAIRS = [
  [[6,42,58],   [255,217,160]],   // Teal / Peach
  [[4,20,58],   [255,154,61]],    // Blue / Orange
  [[26,10,58],  [255,225,77]],    // Purple / Yellow
  [[42,10,42],  [77,240,255]],    // Magenta / Cyan
  [[4,34,15],   [255,143,208]],   // Green / Pink
  [[0,0,0],     [255,255,255]],   // Mono
];
